# Generated by Django 2.2.13 on 2020-06-21 00:14

from django.db import migrations
import ipaddress


def forwards_func(apps, schema_editor):
    FBReport = apps.get_model("dmarc", "FBReport")
    Record = apps.get_model("dmarc", "Record")

    for row in FBReport.objects.all():
        print(row, row.source_ip)
        row.source_ip_tmp = ipaddress.ip_address(row.source_ip)
        row.save(update_fields=['source_ip_tmp'])

    for row in Record.objects.all():
        row.source_ip_tmp = row.source_ip
        row.save(update_fields=['source_ip_tmp'])


# trying to go backwards dosn't work
# something to do with creating source_ip with null=False
# somehow.
def reverse_func(apps, schema_editor):
    FBReport = apps.get_model("dmarc", "FBReport")
    Record = apps.get_model("dmarc", "Record")

    for row in FBReport.objects.all():
        row.source_ip = str(row.source_ip_tmp)
        row.save(update_fields=['source_ip'])

    for row in Record.objects.all():
        row.source_ip = str(row.source_ip_tmp)
        row.save(update_fields=['source_ip'])


class Migration(migrations.Migration):

    dependencies = [
        ('dmarc', '0002_netfields_start'),
    ]

    operations = [
        # run python,
        migrations.RunPython(forwards_func, reverse_func),
    ]
