# Generated by Django 2.2.13 on 2020-06-21 00:14

import django.contrib.postgres.indexes
from django.db import migrations
import netfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dmarc', '0003_netfields_migrate_data'),
    ]

    operations = [
        # delete source_ip,
        migrations.RemoveField(
            model_name='fbreport',
            name='source_ip',
        ),
        migrations.RemoveField(
            model_name='record',
            name='source_ip',
        ),

        # rename source_ip_tmp,
        migrations.RenameField(
            model_name='fbreport',
            old_name='source_ip_tmp',
            new_name='source_ip'
        ),
        migrations.RenameField(
            model_name='record',
            old_name='source_ip_tmp',
            new_name='source_ip'
        ),

        # make null=False
        migrations.AlterField(
            model_name='fbreport',
            name='source_ip',
            field=netfields.fields.InetAddressField(max_length=39),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='record',
            name='source_ip',
            field=netfields.fields.InetAddressField(max_length=39),
            preserve_default=True,
        ),

        # finally add indexes
        migrations.AddIndex(
            model_name='fbreport',
            index=django.contrib.postgres.indexes.GistIndex(
                fields=['source_ip'],
                name='dmarc_fbreport_source_ip_idx',
                opclasses=('inet_ops',)
            ),
        ),
        migrations.AddIndex(
            model_name='record',
            index=django.contrib.postgres.indexes.GistIndex(
                fields=['source_ip'],
                name='dmarc_record_source_ip_idx',
                opclasses=('inet_ops',)
            ),
        ),
    ]
